[package]
name = "dojo_snf_test"
description = "Testing library for Dojo using snfoundry test runner."

version = "1.6.0"
edition = "2024_07"
cairo-version = "=2.11.4"

[dependencies]
starknet = "=2.11.4"
snforge_std = "0.40.0"
assert_macros = "2.11.4"

dojo = { path = "../core" }

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[lib]
