[package]
name = "dojo_macros"
edition.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true
homepage.workspace = true
version.workspace = true
description = """
Cairo proc macros for the Dojo framework.
"""
keywords = ["dojo", "cairo", "starknet", "web3"]
exclude = [".github/**", "images/**"]

[lib]
crate-type = ["rlib","cdylib"]

[dependencies]
anyhow.workspace = true
dojo-types.workspace = true
cairo-lang-primitive-token.workspace = true
cairo-lang-macro.workspace = true
cairo-lang-parser.workspace = true
cairo-lang-utils.workspace = true
cairo-lang-syntax.workspace = true
cairo-lang-defs.workspace = true
cairo-lang-diagnostics.workspace = true
smol_str.workspace = true

cainome.workspace = true
cainome-cairo-serde.workspace = true
starknet-crypto.workspace = true
starknet.workspace = true
regex.workspace = true
itertools.workspace = true
