[package]
edition.workspace = true
license-file.workspace = true
name = "torii-grpc"
repository.workspace = true
version.workspace = true

[dependencies]
bytes = "1.0"
dojo-types = { path = "../../dojo-types" }
futures-util = "0.3.28"
futures.workspace = true
parking_lot.workspace = true
rayon.workspace = true
starknet-crypto.workspace = true
starknet.workspace = true
thiserror.workspace = true
torii-core = { path = "../core", optional = true }

serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
crypto-bigint.workspace = true

# server
hex.workspace = true
hyper = "0.14.27"
rand = "0.8.5"
serde_json.workspace = true
tower = "0.4.13"
tracing.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
tonic-web-wasm-client.workspace = true
wasm-prost.workspace = true
wasm-tonic.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
prost.workspace = true
sqlx.workspace = true
tokio-stream = "0.1.14"
tokio.workspace = true
tonic-reflection.workspace = true
tonic-web.workspace = true
tonic.workspace = true
url.workspace = true

[build-dependencies]
tonic-build.workspace = true
wasm-tonic-build.workspace = true

[features]
client = [  ]
server = [ "dep:torii-core" ] # this feature can't be build on wasm32
