kind = "DojoContract"
class_hash = "0xbfaafc36111f7cc26ed8616dae151bc891142fef3a35090378262b0fb1bb3e"
original_class_hash = "0xbfaafc36111f7cc26ed8616dae151bc891142fef3a35090378262b0fb1bb3e"
base_class_hash = "0x0"
abi = "manifests/release/abis/base/contracts/dojo_examples-mock_token-31599eb2.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-mock_token"
manifest_name = "dojo_examples-mock_token-31599eb2"
