[package]
cairo-version = "2.3.1"
description = "Implementations of ERC standards for the Dojo framework"
name = "dojo_erc"
version = "0.3.3"

[cairo]
sierra-replace-ids = true

[lib]

[dependencies]
dojo = { path = "../dojo-core" }

[scripts]
build = "sozo build"
migrate = "sozo migrate"
test = "sozo test"

# Generate targets/manifest with sozo
[[target.dojo]]


[tool.dojo.env]
# Katana
rpc_url = "http://localhost:5050"
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x4cb5561a3a2a19d14f67f71a9da59c9194e2bbb44e1774260a111094fbd8f39"