[world]
seed = "types_test"
name = "types test"
description = "Graphql types testing"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
# website = "https://dojoengine.org"
# socials.x = "https://twitter.com/dojostarknet"

[namespaces]
default = "types_test"

[env]
account_address = "0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050/"
