[package]
cairo-version = "=2.10.1"
edition = "2024_07"
name = "types_test"
version = "1.4.2"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { path = "../../dojo/core" }

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]
