[package]
cairo-version = "=2.7.0"
edition = "2024_07"
name = "types_test"
version = "1.0.0-alpha.4"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { path = "../../dojo/core" }

[[target.dojo]]
build-external-contracts = [  ]
