[package]
cairo-version = "2.4.0"
name = "types_test"
version = "0.5.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { path = "../../dojo-core" }

[[target.dojo]]
build-external-contracts = [  ]

#[tool.dojo.world]
#name = "types-test"
#description = "Graphql types testing"
# icon_uri = "file://assets/icon.png"
# cover_uri = "file://assets/cover.png"
# website = "https://dojoengine.org"
# socials.x = "https://twitter.com/dojostarknet"

[tool.dojo.env]
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
rpc_url = "http://localhost:5050/"
