[world]
kind = "WorldContract"
class_hash = "0x28c727264c1c1f6550cbaaa7f817039454899dd0bf32a94ff7c814515f67fb3"
original_class_hash = "0x28c727264c1c1f6550cbaaa7f817039454899dd0bf32a94ff7c814515f67fb3"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x5ceb94c01aab2606c2ba56d37578b8451aca5e210c5776075ef8a52ee9c1acb"
transaction_hash = "0x3ac07d801954d5dff176c85dd299e6ab1dcd913eb8316c3e667f469a73f9e1b"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo_world_world"
artifact_name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
manifest_name = "dojo_base_base"
artifact_name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x5c70a663d6b48d8e4c6aaa9572e3735a732ac3765700d470463e670587852af"
class_hash = "0x386b6b90ce188fb732305f8742885ae2fb12f120d2616d6b4d396a0fcdf3590"
original_class_hash = "0x386b6b90ce188fb732305f8742885ae2fb12f120d2616d6b4d396a0fcdf3590"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples-actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "actions"
namespace = "dojo_examples"
manifest_name = "dojo_examples-actions"
artifact_name = "dojo_examples::actions::actions"

[[contracts]]
kind = "DojoContract"
address = "0x7cfff5cd7759cb2d8c301ee20751c4cd6080605055f117c06dc46ee0f92356b"
class_hash = "0x7416f8bb5be2b448d8cb5ef6af84e2a9f63f54c68fd3b04537b6a56d3fdbbf9"
original_class_hash = "0x7416f8bb5be2b448d8cb5ef6af84e2a9f63f54c68fd3b04537b6a56d3fdbbf9"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples-mock_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mock_token"
namespace = "dojo_examples"
manifest_name = "dojo_examples-mock_token"
artifact_name = "dojo_examples::mock_token::mock_token"

[[contracts]]
kind = "DojoContract"
address = "0x64c941606ade888af5eba4e1d6044718edf53b52faeb43ff9233f17f543e967"
class_hash = "0x3fc738cd153b59715c5c0f3ba57265d86f838610d8926b872b402b74ffaa983"
original_class_hash = "0x3fc738cd153b59715c5c0f3ba57265d86f838610d8926b872b402b74ffaa983"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples-others.json"
reads = []
writes = []
computed = []
init_calldata = [
    "$contract_address:dojo_examples:actions",
    "$class_hash:dojo_examples:actions",
    "10",
]
name = "others"
namespace = "dojo_examples"
manifest_name = "dojo_examples-others"
artifact_name = "dojo_examples::others::others"

[[models]]
kind = "DojoModel"
class_hash = "0x422d29e9d76703627b6e17ec21f76ea51673181cca1db86fe3831e6b9520947"
original_class_hash = "0x422d29e9d76703627b6e17ec21f76ea51673181cca1db86fe3831e6b9520947"
abi = "manifests/dev/abis/deployments/models/dojo_examples-contract_initialized.json"
name = "ContractInitialized"
namespace = "dojo_examples"
manifest_name = "dojo_examples-contract_initialized"
artifact_name = "dojo_examples::others::others::contract_initialized"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x15bb4dfdcfe3dae6ee09cd2912b87f341cb0049c448443c19dff53e1dd2b2e4"
original_class_hash = "0x15bb4dfdcfe3dae6ee09cd2912b87f341cb0049c448443c19dff53e1dd2b2e4"
abi = "manifests/dev/abis/deployments/models/dojo_examples-message.json"
name = "Message"
namespace = "dojo_examples"
manifest_name = "dojo_examples-message"
artifact_name = "dojo_examples::models::message"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x7b8abdeec63fe60338f5fd160c747c5db5fd911013a1f9c2b15e88900fabc5b"
original_class_hash = "0x7b8abdeec63fe60338f5fd160c747c5db5fd911013a1f9c2b15e88900fabc5b"
abi = "manifests/dev/abis/deployments/models/dojo_examples-mock_token.json"
name = "MockToken"
namespace = "dojo_examples"
manifest_name = "dojo_examples-mock_token"
artifact_name = "dojo_examples::models::mock_token"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1ea2333b6b366988a726f8b95472b38a56506631d916b38a503b57f7dc2c16b"
original_class_hash = "0x1ea2333b6b366988a726f8b95472b38a56506631d916b38a503b57f7dc2c16b"
abi = "manifests/dev/abis/deployments/models/dojo_examples-moved.json"
name = "Moved"
namespace = "dojo_examples"
manifest_name = "dojo_examples-moved"
artifact_name = "dojo_examples::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x276c8225a5addbfe3e6b38d8e288dc977bdce2e2401877c58783d75c61a9f21"
original_class_hash = "0x276c8225a5addbfe3e6b38d8e288dc977bdce2e2401877c58783d75c61a9f21"
abi = "manifests/dev/abis/deployments/models/dojo_examples-moves.json"
name = "Moves"
namespace = "dojo_examples"
manifest_name = "dojo_examples-moves"
artifact_name = "dojo_examples::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1adabc0c605f4cbbad71bbbb86b8da6b964d406103cc854787e627eb779e474"
original_class_hash = "0x1adabc0c605f4cbbad71bbbb86b8da6b964d406103cc854787e627eb779e474"
abi = "manifests/dev/abis/deployments/models/dojo_examples-player_config.json"
name = "PlayerConfig"
namespace = "dojo_examples"
manifest_name = "dojo_examples-player_config"
artifact_name = "dojo_examples::models::player_config"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xdf544463099a54b4ff5b10473cd62cb56565641d7f6413fe7a499a240f2aac"
original_class_hash = "0xdf544463099a54b4ff5b10473cd62cb56565641d7f6413fe7a499a240f2aac"
abi = "manifests/dev/abis/deployments/models/dojo_examples-position.json"
name = "Position"
namespace = "dojo_examples"
manifest_name = "dojo_examples-position"
artifact_name = "dojo_examples::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
