[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x7efebb0c2d4cc285d48a97a7174def3be7fdd6b7bd29cca758fa2e17e03ef30"
transaction_hash = "0x60316eb232789f4d8352c6afdc36b76d33362d72b43bf78183b43f196779a9d"
block_number = 3
seed = "dojo_examples"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x5c70a663d6b48d8e4c6aaa9572e3735a732ac3765700d470463e670587852af"
class_hash = "0x7d70dda5cb8dcb697ccc2c129254c554e8994f1b231527f7641a14706af016f"
original_class_hash = "0x7d70dda5cb8dcb697ccc2c129254c554e8994f1b231527f7641a14706af016f"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples_actions_actions.json"
reads = []
writes = [
    "Moves",
    "Position",
]
computed = []
init_calldata = []
name = "dojo_examples::actions::actions"

[[contracts]]
kind = "DojoContract"
address = "0x75961b2027c52948ecebfd347aa427436ea308d41997fa9b3c98380f7011d53"
class_hash = "0x5c32bc974f96f82ded691bb95bf26b2783f874fffb50fe84a331acb75ecf5b2"
original_class_hash = "0x5c32bc974f96f82ded691bb95bf26b2783f874fffb50fe84a331acb75ecf5b2"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples_mock_token_mock_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "dojo_examples::mock_token::mock_token"

[[contracts]]
kind = "DojoContract"
address = "0x3f51cd82daaf5907d2fd082ae3f45ae2ef96ab61677f46abc16e0a54d3392d1"
class_hash = "0x3ee016157303a7ce35a9fecdb5b8519159df620c5780527d61443636aaa3c3a"
original_class_hash = "0x3ee016157303a7ce35a9fecdb5b8519159df620c5780527d61443636aaa3c3a"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples_others_others.json"
reads = []
writes = []
computed = []
init_calldata = [
    "$contract_address:dojo_examples::actions::actions",
    "$class_hash:dojo_examples::actions::actions",
    "10",
]
name = "dojo_examples::others::others"

[[models]]
kind = "DojoModel"
class_hash = "0x4ef89963afe500337aaf757ad52394ea8e311077a825b3de5a5f32d3457997c"
original_class_hash = "0x4ef89963afe500337aaf757ad52394ea8e311077a825b3de5a5f32d3457997c"
abi = "manifests/dev/abis/deployments/models/dojo_examples_actions_actions_moved.json"
name = "dojo_examples::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x33bdb1a470ea0ee7d77faa3c75151934b3b129c0bad7333ec6c2dad1b98ec5"
original_class_hash = "0x33bdb1a470ea0ee7d77faa3c75151934b3b129c0bad7333ec6c2dad1b98ec5"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_message.json"
name = "dojo_examples::models::message"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x6a21c56878ba470ac7a51f336ca6a59781de38e1810d2d20866ab2b52138a6d"
original_class_hash = "0x6a21c56878ba470ac7a51f336ca6a59781de38e1810d2d20866ab2b52138a6d"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_mock_token.json"
name = "dojo_examples::models::mock_token"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x456d85286b34249fffa0a13d1ac490cc1f5b02eb1a1c92d820c59d6b0f2eaa8"
original_class_hash = "0x456d85286b34249fffa0a13d1ac490cc1f5b02eb1a1c92d820c59d6b0f2eaa8"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_moves.json"
name = "dojo_examples::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x584d016a91d077c86ff1c014e0c4d735946d1084dd0d4c0a80cee6d04629e55"
original_class_hash = "0x584d016a91d077c86ff1c014e0c4d735946d1084dd0d4c0a80cee6d04629e55"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_player_config.json"
name = "dojo_examples::models::player_config"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x27942375b09862291ece780c573e8c625df4ba41fd7524e0658ca75fff014ff"
original_class_hash = "0x27942375b09862291ece780c573e8c625df4ba41fd7524e0658ca75fff014ff"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_position.json"
name = "dojo_examples::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6dc51a232ffcfaa02646636daf1b8acab8121fa69458258da8df1620aff07ab"
original_class_hash = "0x6dc51a232ffcfaa02646636daf1b8acab8121fa69458258da8df1620aff07ab"
abi = "manifests/dev/abis/deployments/models/dojo_examples_models_server_profile.json"
name = "dojo_examples::models::server_profile"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "server_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4b29afc6db744bd87f7276869620348557c11b984e9f3fcb27c4d55efb0ab6c"
original_class_hash = "0x4b29afc6db744bd87f7276869620348557c11b984e9f3fcb27c4d55efb0ab6c"
abi = "manifests/dev/abis/deployments/models/dojo_examples_others_others_contract_initialized.json"
name = "dojo_examples::others::others::contract_initialized"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false
