[world]
kind = "WorldContract"
class_hash = "0x1498dd1197805ec05d37da956d0fc568023a4c25578b0523b4f4f0d0e4f16c2"
original_class_hash = "0x1498dd1197805ec05d37da956d0fc568023a4c25578b0523b4f4f0d0e4f16c2"
abi = "abis/deployments/dojo-world.json"
address = "0x104dd156d76aeab45146a10869637f161ca6cf9f804704f8bbb12ae5b1b5cfb"
transaction_hash = "0x280e50610d4467bfe1be1adaae7f77642adbe2ad4106cb861e28441e94ff287"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/base/dojo-base.json"
tag = "dojo:base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2a570e12405096e725508ba1f4ade127edd42e0fcb5890b8f12f76ef043623"
class_hash = "0x7b39442bf860c74e8c3dae198623c996c4c24c6d442735d5be20cc58ce15e4e"
original_class_hash = "0x7b39442bf860c74e8c3dae198623c996c4c24c6d442735d5be20cc58ce15e4e"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "abis/deployments/contracts/dojo_examples-actions-49cbe40e.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples:actions"
manifest_name = "dojo_examples-actions-49cbe40e"

[[contracts]]
kind = "DojoContract"
address = "0x26f33e8d81dad06c79c2d944ea519a850e007eb8432ae20d38db82caea590b2"
class_hash = "0x35cec8c62ba7a93be10ec69e8e8a0e3963b83873dc0679102f20e011a3dae94"
original_class_hash = "0x35cec8c62ba7a93be10ec69e8e8a0e3963b83873dc0679102f20e011a3dae94"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "abis/deployments/contracts/dojo_examples-mock_token-1e060b45.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples:mock_token"
manifest_name = "dojo_examples-mock_token-1e060b45"

[[contracts]]
kind = "DojoContract"
address = "0x3304896afaa421f362b3b8e8586773f9a7fcaca050b3fd6885400908803f344"
class_hash = "0x6e4c6cc2e7bc17b82246ee99a3b2a3dcb5d7dd8f7666858e0baa86a1e2ac4f6"
original_class_hash = "0x6e4c6cc2e7bc17b82246ee99a3b2a3dcb5d7dd8f7666858e0baa86a1e2ac4f6"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "abis/deployments/contracts/dojo_examples-others-1297eb86.json"
reads = []
writes = []
computed = []
init_calldata = [
    "$contract_address:dojo_examples:actions",
    "$class_hash:dojo_examples:actions",
    "10",
]
tag = "dojo_examples:others"
manifest_name = "dojo_examples-others-1297eb86"

[[models]]
kind = "DojoModel"
class_hash = "0x37b7d94c2c6a4284b109149f76349ba513cf5459e46f3688a875c4921eab510"
original_class_hash = "0x37b7d94c2c6a4284b109149f76349ba513cf5459e46f3688a875c4921eab510"
abi = "abis/deployments/models/dojo_examples-ContractInitialized-56eeab26.json"
tag = "dojo_examples:ContractInitialized"
manifest_name = "dojo_examples-ContractInitialized-56eeab26"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x60a1c33b918cb63ec0842285b67ae18dd6ba22a95baaaceffb370db630eeaa4"
original_class_hash = "0x60a1c33b918cb63ec0842285b67ae18dd6ba22a95baaaceffb370db630eeaa4"
abi = "abis/deployments/models/dojo_examples-Message-2b1e4414.json"
tag = "dojo_examples:Message"
manifest_name = "dojo_examples-Message-2b1e4414"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x5c18f631d0a009b44cd7b3ef25e4ab240d22a995843511d1d924056f2e3d895"
original_class_hash = "0x5c18f631d0a009b44cd7b3ef25e4ab240d22a995843511d1d924056f2e3d895"
abi = "abis/deployments/models/dojo_examples-MockToken-14cc132d.json"
tag = "dojo_examples:MockToken"
manifest_name = "dojo_examples-MockToken-14cc132d"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x8099d73f0af5737215041df37d770768fba4265b9a68de9c4e02d49bfaa1c5"
original_class_hash = "0x8099d73f0af5737215041df37d770768fba4265b9a68de9c4e02d49bfaa1c5"
abi = "abis/deployments/models/dojo_examples-Moved-6a1e458e.json"
tag = "dojo_examples:Moved"
manifest_name = "dojo_examples-Moved-6a1e458e"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3cbcfee00a2e31140eb046e290926355f64f763c99ac18a81636c73bc35d4ec"
original_class_hash = "0x3cbcfee00a2e31140eb046e290926355f64f763c99ac18a81636c73bc35d4ec"
abi = "abis/deployments/models/dojo_examples-Moves-5e0bed36.json"
tag = "dojo_examples:Moves"
manifest_name = "dojo_examples-Moves-5e0bed36"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x54c9f0eb172362bb3b69499d0a3ff634d52cfc8909b38713bd6872467fec76a"
original_class_hash = "0x54c9f0eb172362bb3b69499d0a3ff634d52cfc8909b38713bd6872467fec76a"
abi = "abis/deployments/models/dojo_examples-PlayerConfig-2d357dac.json"
tag = "dojo_examples:PlayerConfig"
manifest_name = "dojo_examples-PlayerConfig-2d357dac"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4cc7ad8362c56d99136d6f814aa9ab924ed50b5cdc5269fa8a536ee0f8b4bd2"
original_class_hash = "0x4cc7ad8362c56d99136d6f814aa9ab924ed50b5cdc5269fa8a536ee0f8b4bd2"
abi = "abis/deployments/models/dojo_examples-Position-6694bf61.json"
tag = "dojo_examples:Position"
manifest_name = "dojo_examples-Position-6694bf61"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x66a806d59e69873946a5b06e0e3df94c2f9cb139d8cc32f73e4f9ebc0ff885"
original_class_hash = "0x66a806d59e69873946a5b06e0e3df94c2f9cb139d8cc32f73e4f9ebc0ff885"
abi = "abis/deployments/models/dojo_examples-ServerProfile-71e0f153.json"
tag = "dojo_examples:ServerProfile"
manifest_name = "dojo_examples-ServerProfile-71e0f153"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "server_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false
