[package]
edition.workspace = true
name = "sozo-mcp"
version = "1.8.3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "sozo-mcp"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
camino.workspace = true
dojo-types.workspace = true
dojo-world.workspace = true
scarb-metadata.workspace = true
scarb-metadata-ext.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
tokio.workspace = true
itertools.workspace = true

# Use dev version of rmcp.
rmcp = { git = "https://github.com/modelcontextprotocol/rust-sdk", rev = "e6effb327883d0a8a91f5efbb527194747eee57b", features = ["server", "transport-io"] }
# This is currently required to ensure that the `derive` feature works. rmcp fails to compile otherwise.
schemars = { version = "0.8.22", features = ["derive"] }

[dev-dependencies]
tempfile = "3.8"
tokio = { workspace = true, features = ["full", "test-util"] }
serde_json = { workspace = true }
dojo-test-utils.workspace = true
