[package]
edition.workspace = true
license.workspace = true
name = "katana-node"
repository.workspace = true
version.workspace = true

[dependencies]
katana-chain-spec.workspace = true
katana-core.workspace = true
katana-db.workspace = true
katana-executor.workspace = true
katana-pipeline.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-rpc.workspace = true
katana-rpc-api.workspace = true
katana-stage.workspace = true
katana-tasks.workspace = true

anyhow.workspace = true
dojo-metrics.workspace = true
futures.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
thiserror.workspace = true
toml.workspace = true
tower = { workspace = true, features = [ "full" ] }
tower-http = { workspace = true, features = [ "full" ] }
tracing.workspace = true
url.workspace = true

const_format = "0.2.33"
strum.workspace = true
strum_macros.workspace = true

clap = { workspace = true, optional = true }
dojo-utils = { workspace = true, optional = true }
katana-feeder-gateway = { workspace = true, optional = true }
katana-provider = { workspace = true, optional = true }
tokio = { workspace = true, features = [ "time" ], optional = true }
tracing-log = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

[build-dependencies]
vergen = { version = "9.0.0", features = [ "build", "cargo", "emit_and_set" ] }
vergen-gitcl = { version = "1.0.0", features = [ "build", "cargo", "rustc", "si" ] }

[features]
# experimental feature to test katana full node mode
full-node = [ "dep:katana-feeder-gateway", "dep:katana-provider", "dep:tokio" ]

[[bin]]
name = "full-node"
path = "src/full/node.rs"
required-features = [
	"clap",
	"dojo-utils",
	"full-node",
	"tracing-log",
	"tracing-subscriber",
]
