[package]
description = "Types used in Katana RPC layer."
edition.workspace = true
name = "katana-rpc-types"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katana-core = { path = "../../core" }
katana-primitives = { path = "../../primitives" }
katana-provider = { path = "../../storage/provider" }

anyhow.workspace = true
derive_more.workspace = true
jsonrpsee = { workspace = true, features = [ "macros", "server" ] }
serde.workspace = true
serde_with.workspace = true
starknet.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
