[package]
description = "Types used in Katana RPC layer."
edition.workspace = true
name = "katana-rpc-types"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katana-cairo.workspace = true
katana-core.workspace = true
katana-executor.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-trie.workspace = true

anyhow.workspace = true
derive_more.workspace = true
futures.workspace = true
jsonrpsee = { workspace = true, features = [ "server" ] }
num-traits.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
starknet.workspace = true
starknet-crypto.workspace = true
thiserror.workspace = true

alloy-primitives.workspace = true
flate2.workspace = true
serde_json_pythonic = "0.1.2"
similar-asserts.workspace = true

cainome-cairo-serde.workspace = true
cainome.workspace = true

[dev-dependencies]
rstest.workspace = true
