[package]
edition.workspace = true
license-file.workspace = true
name = "dojo-examples-spawn-and-move"
repository.workspace = true
version.workspace = true

[package.metadata.release]
pre-release-replacements = [
	{ file = "Scarb.lock", search = "^name = \"dojo\"\nversion = \".*\"$", replace = "name = \"dojo\"\nversion = \"{{version}}\"", min = 1 },
	{ file = "Scarb.toml", search = "^version = \".*\"$", replace = "version = \"{{version}}\"", min = 1 },
]

[lib]
path = "src/lib.rs"
