[world]
description = "example world"
name = "example"
seed = "dojo_examples"

[[models]]
tag = "ns-Message"
description = "Message sent by a player"

[[models]]
tag = "ns-Position"
description = "position of a player in the world"

[[models]]
tag = "ns-Moves"
description = "move of a player in the world"

[[events]]
tag = "ns-Moved"
description = "when a player has moved"

[[contracts]]
tag = "ns-actions"
description = "set of actions for a player"

[namespace]
default = "ns"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x2af9427c5a277474c079a1283c880ee8a6f0f8fbf73ce969c08d88befec1bba"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
world_address = "0x5d2547a660f585d31c9e8b53fc916ab22fc97a6d1c4d8fcd8fb12d1c20f9952"
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"

[init_call_args]
"ns-others" = ["0xff"]

[writers]
"ns" = [ "ns-mock_token", "ns-actions", "ns-others" ]
