kind = "Class"
class_hash = "0x26a8f65e0b0ba2a6d2f9e93d4f72f75eabebb853ea7413e134b3902ea352557"
original_class_hash = "0x26a8f65e0b0ba2a6d2f9e93d4f72f75eabebb853ea7413e134b3902ea352557"
abi = "manifests/release/base/abis/dojo-world.json"
tag = "dojo-world"
manifest_name = "dojo-world"
