kind = "DojoModel"
class_hash = "0x720bb4a3a1324dea862ac8b3ac3e30ac55490ce6ec9f7f68341db081b290c08"
original_class_hash = "0x720bb4a3a1324dea862ac8b3ac3e30ac55490ce6ec9f7f68341db081b290c08"
abi = "manifests/release/base/abis/models/dojo_examples-ContractInitialized-376b7bd6.json"
tag = "dojo_examples-ContractInitialized"
qualified_path = "dojo_examples::others::others::contract_initialized"
manifest_name = "dojo_examples-ContractInitialized-376b7bd6"

[[members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[members]]
name = "contract_class"
type = "ClassHash"
key = false

[[members]]
name = "value"
type = "u8"
key = false
