kind = "DojoModel"
class_hash = "0x783cecd986c0f03f8ac70318f67d57ea8072db7d4d135d54585f4de33c879ad"
original_class_hash = "0x783cecd986c0f03f8ac70318f67d57ea8072db7d4d135d54585f4de33c879ad"
abi = "manifests/release/base/abis/models/dojo_examples_weapons-Flatbow-22f5bd16.json"
tag = "dojo_examples_weapons-Flatbow"
qualified_path = "armory::flatbow"
manifest_name = "dojo_examples_weapons-Flatbow-22f5bd16"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "atk_speek"
type = "u32"
key = false

[[members]]
name = "range"
type = "u32"
key = false
