[package]
cairo-version = "2.2.0"
name = "dojo_examples"
version = "0.2.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { path = "../../crates/dojo-core" }
# dojo_erc = { path = "../../crates/dojo-erc" }

[[target.dojo]]
build-external-contracts = [
    # "dojo_erc::erc721::components::Balance",
    # "dojo_erc::erc721::components::OperatorApproval",
    # "dojo_erc::erc721::components::Owner",
    # "dojo_erc::erc721::components::TokenApproval",
    # "dojo_erc::erc721::erc721::ERC721",
    # "dojo_erc::erc721::systems::erc721_approve",
    # "dojo_erc::erc721::systems::erc721_burn",
    # "dojo_erc::erc721::systems::erc721_mint",
    # "dojo_erc::erc721::systems::erc721_set_approval_for_all",
    # "dojo_erc::erc721::systems::erc721_transfer_from",
]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"

# Default account for katana with seed = 0
account_address = "0x517ececd29116499f4a1b64b094da79ba08dfd54a3edaa316134c41f8160973"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"
