[package]
description = "Torii core implementation."
edition.workspace = true
license-file.workspace = true
name = "torii-core"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
cainome.workspace = true
chrono.workspace = true
crypto-bigint.workspace = true
dojo-types = { path = "../../dojo-types" }
dojo-world = { path = "../../dojo-world", features = [ "contracts", "manifest" ] }
futures-channel = "0.3.0"
futures-util.workspace = true
hex.workspace = true
lazy_static.workspace = true
log.workspace = true
once_cell.workspace = true
reqwest.workspace = true
scarb-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
slab = "0.4.2"
sozo-ops.workspace = true
sqlx.workspace = true
starknet-crypto.workspace = true
starknet.workspace = true
thiserror.workspace = true
tokio = { version = "1.32.0", features = [ "sync" ], default-features = true }
tokio-stream = "0.1.11"
tokio-util = "0.7.7"
tracing.workspace = true

[dev-dependencies]
camino.workspace = true
dojo-test-utils = { path = "../../dojo-test-utils" }
katana-runner.workspace = true
scarb.workspace = true
