[package]
description = "Sozo signer implementations"
edition.workspace = true
license-file.workspace = true
name = "sozo-signers"
repository.workspace = true
version = "1.8.0"

[dependencies]
anyhow.workspace = true
starknet.workspace = true
