[world]
kind = "WorldContract"
class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
original_class_hash = "0x6f4515274ee23404789c3351a77107d0ec07508530119822046600ca6948d6e"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x5fedbace16902d9ca4cdc1522f9fe156cd8c69a5d25e1436ee4b7b9933ad997"
transaction_hash = "0x506e4efa5fa9ce5808a482b7076db8ca707a013bafaebf089206f28cd5f6bb6"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x3287947f8080cdf20c0a6e88d50a8d824e04f035bd34550316e6768d87d35de"
class_hash = "0x67a20ea91a4b9bb9cdb46cefc41dd6ca4c07c22d4d413205720963944fd817d"
original_class_hash = "0x67a20ea91a4b9bb9cdb46cefc41dd6ca4c07c22d4d413205720963944fd817d"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = ["ns:dojo_examples"]
init_calldata = []
tag = "dojo_examples-actions"
systems = [
    "set_models",
    "spawn",
    "move",
    "set_player_config",
    "reset_player_config",
    "set_player_server_profile",
    "enter_dungeon",
    "update_player_name",
    "update_player_items",
]
manifest_name = "dojo_examples-actions-40b6994c"

[[contracts]]
kind = "DojoContract"
address = "0x6ee438f6082f930c1b874cfefa2e380b1bd8eb8d77374bf18e8224c5dd1819"
class_hash = "0x4590a27e4ec7366358ba5f60323777f301435ebbdd113ab02c54b947717530d"
original_class_hash = "0x4590a27e4ec7366358ba5f60323777f301435ebbdd113ab02c54b947717530d"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-dungeon-6620e0e6.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-dungeon"
systems = ["enter"]
manifest_name = "dojo_examples-dungeon-6620e0e6"

[[contracts]]
kind = "DojoContract"
address = "0xd9e080358f8bcb8ca52182623e63b4777dbf54dedd3742bd86fabb3d1991ba"
class_hash = "0x67edb33671cd2f5b766d073e3dec53b03400761a20f349ea9628cf4c883b393"
original_class_hash = "0x67edb33671cd2f5b766d073e3dec53b03400761a20f349ea9628cf4c883b393"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-mock_token-31599eb2.json"
reads = []
writes = ["ns:dojo_examples"]
init_calldata = []
tag = "dojo_examples-mock_token"
systems = []
manifest_name = "dojo_examples-mock_token-31599eb2"

[[contracts]]
kind = "DojoContract"
address = "0x3fec924b42052f14a9c4bb48abae2068d66034e3cc6e063353b87a5659f5040"
class_hash = "0x40e824b8814bafef18cce2cf68f5765e9c9a1c86f55a8491b0c2a4faebdcc87"
original_class_hash = "0x40e824b8814bafef18cce2cf68f5765e9c9a1c86f55a8491b0c2a4faebdcc87"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
init_calldata = [
    "$contract_address:dojo_examples-actions",
    "$class_hash:dojo_examples-actions",
    "10",
]
tag = "dojo_examples-others"
systems = []
manifest_name = "dojo_examples-others-61de2c18"

[[models]]
kind = "DojoModel"
class_hash = "0x3869ae2b02ccbe974e2c468114f4bf6147e85eedf9591ba05022c3c6da65421"
original_class_hash = "0x3869ae2b02ccbe974e2c468114f4bf6147e85eedf9591ba05022c3c6da65421"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ContractInitialized-376b7bd6.json"
tag = "dojo_examples-ContractInitialized"
qualified_path = "dojo_examples::others::others::dojo_examples__contract_initialized"
manifest_name = "dojo_examples-ContractInitialized-376b7bd6"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x70b97da7c4232af42e736c1b461c7c6d36f7f16cfead7bde76c742ad6c22dce"
original_class_hash = "0x70b97da7c4232af42e736c1b461c7c6d36f7f16cfead7bde76c742ad6c22dce"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Message-1bb1d226.json"
tag = "dojo_examples-Message"
qualified_path = "dojo_examples::models::dojo_examples__message"
manifest_name = "dojo_examples-Message-1bb1d226"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x3d6c0104c8bfd09d69c0afe27238ef16df64e9bc0eede0920b235765b5b7d31"
original_class_hash = "0x3d6c0104c8bfd09d69c0afe27238ef16df64e9bc0eede0920b235765b5b7d31"
abi = "manifests/dev/deployment/abis/models/dojo_examples-MockToken-38903c7c.json"
tag = "dojo_examples-MockToken"
qualified_path = "dojo_examples::models::dojo_examples__mock_token"
manifest_name = "dojo_examples-MockToken-38903c7c"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x6867c2efb307789f706facd0fe932631057f4a02f063f7d9f0d218633ff4a3b"
original_class_hash = "0x6867c2efb307789f706facd0fe932631057f4a02f063f7d9f0d218633ff4a3b"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moved-318ae40d.json"
tag = "dojo_examples-Moved"
qualified_path = "dojo_examples::actions::actions::dojo_examples__moved"
manifest_name = "dojo_examples-Moved-318ae40d"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x28d469fa541e5343e13c53ed79c40c423060c29b01994cf651c585051ab18a3"
original_class_hash = "0x28d469fa541e5343e13c53ed79c40c423060c29b01994cf651c585051ab18a3"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moves-2e2accba.json"
tag = "dojo_examples-Moves"
qualified_path = "dojo_examples::models::dojo_examples__moves"
manifest_name = "dojo_examples-Moves-2e2accba"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x26270151710a597b55e919e03479192840b39d7ed778eda7b0198ab2aaa823d"
original_class_hash = "0x26270151710a597b55e919e03479192840b39d7ed778eda7b0198ab2aaa823d"
abi = "manifests/dev/deployment/abis/models/dojo_examples-PlayerConfig-3adad785.json"
tag = "dojo_examples-PlayerConfig"
qualified_path = "dojo_examples::models::dojo_examples__player_config"
manifest_name = "dojo_examples-PlayerConfig-3adad785"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x49022c6c42a2c0777747cefcdbb4a7cc5b7335d535b85e39a4ce1f847d84606"
original_class_hash = "0x49022c6c42a2c0777747cefcdbb4a7cc5b7335d535b85e39a4ce1f847d84606"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Position-1e145e26.json"
tag = "dojo_examples-Position"
qualified_path = "dojo_examples::models::dojo_examples__position"
manifest_name = "dojo_examples-Position-1e145e26"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x8719c72387eeb28386e14013bbe347dfb129910a90dc4463d800bc7ca799c7"
original_class_hash = "0x8719c72387eeb28386e14013bbe347dfb129910a90dc4463d800bc7ca799c7"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ServerProfile-4caad1e6.json"
tag = "dojo_examples-ServerProfile"
qualified_path = "dojo_examples::models::dojo_examples__server_profile"
manifest_name = "dojo_examples-ServerProfile-4caad1e6"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "server_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2080f40ebe67d83802c125462ab1c09702e4ffc69a768400f1f67838e91d843"
original_class_hash = "0x2080f40ebe67d83802c125462ab1c09702e4ffc69a768400f1f67838e91d843"
abi = "manifests/dev/deployment/abis/models/dojo_examples_foes-RiverSkale-39535c12.json"
tag = "dojo_examples_foes-RiverSkale"
qualified_path = "bestiary::dojo_examples_foes__river_skale"
manifest_name = "dojo_examples_foes-RiverSkale-39535c12"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "armor"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1ebf97aea2237cd9d376eee372803e02e45f46ca56dc95c2cbd2daa88fcbc82"
original_class_hash = "0x1ebf97aea2237cd9d376eee372803e02e45f46ca56dc95c2cbd2daa88fcbc82"
abi = "manifests/dev/deployment/abis/models/dojo_examples_weapons-Flatbow-22f5bd16.json"
tag = "dojo_examples_weapons-Flatbow"
qualified_path = "armory::dojo_examples_weapons__flatbow"
manifest_name = "dojo_examples_weapons-Flatbow-22f5bd16"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "atk_speek"
type = "u32"
key = false

[[models.members]]
name = "range"
type = "u32"
key = false
