[world]
kind = "WorldContract"
class_hash = "0x210dd8e484e5555dc74a4a600b17878fc108911719b04139309acc874160c51"
original_class_hash = "0x210dd8e484e5555dc74a4a600b17878fc108911719b04139309acc874160c51"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x504b804eeac62e68d12dc030e56b8f62cb047950c346e60a974da02795f6aba"
transaction_hash = "0x65168705b42b38a0b9e290dfb079e023fa1960febb9fd7069fce5e369e3b56f"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x26a4f5d2d9638877a2648297339275df5eaab0adb3cdf0010887c2dbf2be4"
original_class_hash = "0x26a4f5d2d9638877a2648297339275df5eaab0adb3cdf0010887c2dbf2be4"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x2e85647f570d2a4abdffdd668823702548d20d1d6aaef74b6a4eb9670a32798"
class_hash = "0x2c975b0d681861edd6caad5fbc0b42dc3e8b034b6c0b0a7628fb3a7bedf1e8d"
original_class_hash = "0x2c975b0d681861edd6caad5fbc0b42dc3e8b034b6c0b0a7628fb3a7bedf1e8d"
base_class_hash = "0x26a4f5d2d9638877a2648297339275df5eaab0adb3cdf0010887c2dbf2be4"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = [
    "dojo_examples-Moves",
    "dojo_examples-Position",
]
computed = []
init_calldata = []
tag = "dojo_examples-actions"
manifest_name = "dojo_examples-actions-40b6994c"

[[contracts]]
kind = "DojoContract"
address = "0x4f38db968d53b073189760e1256d827195de3904542cf62d60e6bd3707f8504"
class_hash = "0x14b3096b82a761f63dd47277c2b5ac18925dea43586418483939a2f1f57f674"
original_class_hash = "0x14b3096b82a761f63dd47277c2b5ac18925dea43586418483939a2f1f57f674"
base_class_hash = "0x26a4f5d2d9638877a2648297339275df5eaab0adb3cdf0010887c2dbf2be4"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-dungeon-6620e0e6.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-dungeon"
manifest_name = "dojo_examples-dungeon-6620e0e6"

[[contracts]]
kind = "DojoContract"
address = "0x6a06eb156f956f1691bce4a4573c97b1a5f08d3bfa65fc25c4ed4b55d3e61a1"
class_hash = "0x97cd4fb3acfe9e6a024589ea34db2fc587586d699ef3732ce627e1771158ef"
original_class_hash = "0x97cd4fb3acfe9e6a024589ea34db2fc587586d699ef3732ce627e1771158ef"
base_class_hash = "0x26a4f5d2d9638877a2648297339275df5eaab0adb3cdf0010887c2dbf2be4"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-mock_token-31599eb2.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-mock_token"
manifest_name = "dojo_examples-mock_token-31599eb2"

[[contracts]]
kind = "DojoContract"
address = "0x6359537114e0a62c63f52f2fb3c0e6241c9a2fcbd9dc9df221c867662aa31e9"
class_hash = "0x479bfb12dcba5398d77303e7a665fc3fedb16f2d7f9cb1f5d7e2beb3b7e2ba7"
original_class_hash = "0x479bfb12dcba5398d77303e7a665fc3fedb16f2d7f9cb1f5d7e2beb3b7e2ba7"
base_class_hash = "0x26a4f5d2d9638877a2648297339275df5eaab0adb3cdf0010887c2dbf2be4"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
computed = []
init_calldata = [
    "$contract_address:dojo_examples-actions",
    "$class_hash:dojo_examples-actions",
    "10",
]
tag = "dojo_examples-others"
manifest_name = "dojo_examples-others-61de2c18"

[[models]]
kind = "DojoModel"
class_hash = "0x1da39caefeb15d61baa9d1d71f21ed79cf5650aa215b583e7f453c0d7d4ee65"
original_class_hash = "0x1da39caefeb15d61baa9d1d71f21ed79cf5650aa215b583e7f453c0d7d4ee65"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ContractInitialized-376b7bd6.json"
tag = "dojo_examples-ContractInitialized"
manifest_name = "dojo_examples-ContractInitialized-376b7bd6"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x572bf6d3cbcd69fd6404a993110c3b84379882587b21b7ad5b2761088cb19c3"
original_class_hash = "0x572bf6d3cbcd69fd6404a993110c3b84379882587b21b7ad5b2761088cb19c3"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Message-1bb1d226.json"
tag = "dojo_examples-Message"
manifest_name = "dojo_examples-Message-1bb1d226"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x4463c89586bc5015a7bc97e9e4af123330842b20aa6f6587c795d6d35907a9d"
original_class_hash = "0x4463c89586bc5015a7bc97e9e4af123330842b20aa6f6587c795d6d35907a9d"
abi = "manifests/dev/deployment/abis/models/dojo_examples-MockToken-38903c7c.json"
tag = "dojo_examples-MockToken"
manifest_name = "dojo_examples-MockToken-38903c7c"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x36b7886db455f41fac4263da9f0d21190bb575c8555bde1c3357486495c0be1"
original_class_hash = "0x36b7886db455f41fac4263da9f0d21190bb575c8555bde1c3357486495c0be1"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moved-318ae40d.json"
tag = "dojo_examples-Moved"
manifest_name = "dojo_examples-Moved-318ae40d"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x23ec6500e0f3e8c64c6fb3ee3ed3259d81c0bde627c8c9c1177da098189dd89"
original_class_hash = "0x23ec6500e0f3e8c64c6fb3ee3ed3259d81c0bde627c8c9c1177da098189dd89"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moves-2e2accba.json"
tag = "dojo_examples-Moves"
manifest_name = "dojo_examples-Moves-2e2accba"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x13f8294fde1c2605e9825782ae293b3bae2291e6cbd20d4ef8878ff044d4b82"
original_class_hash = "0x13f8294fde1c2605e9825782ae293b3bae2291e6cbd20d4ef8878ff044d4b82"
abi = "manifests/dev/deployment/abis/models/dojo_examples-PlayerConfig-3adad785.json"
tag = "dojo_examples-PlayerConfig"
manifest_name = "dojo_examples-PlayerConfig-3adad785"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7104c882f56f62ef1f2453319bf6a1f5784b5f33b63b65506c38d62c3e3fd40"
original_class_hash = "0x7104c882f56f62ef1f2453319bf6a1f5784b5f33b63b65506c38d62c3e3fd40"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Position-1e145e26.json"
tag = "dojo_examples-Position"
manifest_name = "dojo_examples-Position-1e145e26"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x48dfe99daae31ced8d121079c148d084311483f047519d2d3fae363f15c7a1f"
original_class_hash = "0x48dfe99daae31ced8d121079c148d084311483f047519d2d3fae363f15c7a1f"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ServerProfile-4caad1e6.json"
tag = "dojo_examples-ServerProfile"
manifest_name = "dojo_examples-ServerProfile-4caad1e6"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "server_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x34e17c9bad7ccfa7286e07ed3a9af0b2922c7ee77a4889a1c59d0a6dd7aeacc"
original_class_hash = "0x34e17c9bad7ccfa7286e07ed3a9af0b2922c7ee77a4889a1c59d0a6dd7aeacc"
abi = "manifests/dev/deployment/abis/models/dojo_examples_foes-RiverSkale-39535c12.json"
tag = "dojo_examples_foes-RiverSkale"
manifest_name = "dojo_examples_foes-RiverSkale-39535c12"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "armor"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x672ce1913b025af73d80030f0e7e8d5fa4debe9b011cf0a39a27514cac4a3b5"
original_class_hash = "0x672ce1913b025af73d80030f0e7e8d5fa4debe9b011cf0a39a27514cac4a3b5"
abi = "manifests/dev/deployment/abis/models/dojo_examples_weapons-Flatbow-22f5bd16.json"
tag = "dojo_examples_weapons-Flatbow"
manifest_name = "dojo_examples_weapons-Flatbow-22f5bd16"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "atk_speek"
type = "u32"
key = false

[[models.members]]
name = "range"
type = "u32"
key = false
