[world]
kind = "WorldContract"
class_hash = "0x27845f1b684041a2dcbba9960206ab0be559dc6acbc324bd1cba7918887e813"
original_class_hash = "0x27845f1b684041a2dcbba9960206ab0be559dc6acbc324bd1cba7918887e813"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x7ddf8574c8715a8e0ca352860099315a7a2f39597ff733f1df479760561a218"
transaction_hash = "0x59bb050f12bdb14186e69c139e5da50a9f60b0d55acd349727b5ac847d2d706"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7f130e487fae5d3b9d947aa2f2002897361f957f3eb38a3c0ea4fa3b06f662c"
class_hash = "0xc0a5037a6fdc0b374b270ca5e9f3bd76200d73d01f409749b7006b3cd6c03d"
original_class_hash = "0xc0a5037a6fdc0b374b270ca5e9f3bd76200d73d01f409749b7006b3cd6c03d"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = [
    "dojo_examples-Moves",
    "dojo_examples-Position",
]
computed = []
init_calldata = []
tag = "dojo_examples-actions"
manifest_name = "dojo_examples-actions-40b6994c"

[[contracts]]
kind = "DojoContract"
address = "0x50edd2f7b372b0551edacf628064e4eb8ac44150697ae9159ee2a130a532fac"
class_hash = "0x45ad5a298db270a9c3ee439b7a7a008e3219b70937cfaa144589866442f3908"
original_class_hash = "0x45ad5a298db270a9c3ee439b7a7a008e3219b70937cfaa144589866442f3908"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-dungeon-6620e0e6.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-dungeon"
manifest_name = "dojo_examples-dungeon-6620e0e6"

[[contracts]]
kind = "DojoContract"
address = "0x2730055c4af418e11c058e318ac7668179b2ee60c814041d139f8784ea687cb"
class_hash = "0x2cc02e47b1f2e767ced0fa64afcc481e7e2ad9fad7a8e66921f8452cc44071c"
original_class_hash = "0x2cc02e47b1f2e767ced0fa64afcc481e7e2ad9fad7a8e66921f8452cc44071c"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-mock_token-31599eb2.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-mock_token"
manifest_name = "dojo_examples-mock_token-31599eb2"

[[contracts]]
kind = "DojoContract"
address = "0x263a9083ee28ba1b521b21b33b7588405b4dc484048ef1355c9e2e66a13e500"
class_hash = "0x647fc1b2d2e902e6304e127b36995d8f57fe45c38e38e15d8860db508dbf24a"
original_class_hash = "0x647fc1b2d2e902e6304e127b36995d8f57fe45c38e38e15d8860db508dbf24a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
computed = []
init_calldata = [
    "$contract_address:dojo_examples-actions",
    "$class_hash:dojo_examples-actions",
    "10",
]
tag = "dojo_examples-others"
manifest_name = "dojo_examples-others-61de2c18"

[[models]]
kind = "DojoModel"
class_hash = "0x8a7f15ef119eb0b44c6b7f30f312dc23619d781173dcfff0e55234bf4a67a3"
original_class_hash = "0x8a7f15ef119eb0b44c6b7f30f312dc23619d781173dcfff0e55234bf4a67a3"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ContractInitialized-376b7bd6.json"
tag = "dojo_examples-ContractInitialized"
manifest_name = "dojo_examples-ContractInitialized-376b7bd6"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3ca17c0ebb595e1d1cc01813923864316a49b91f4a725ef1371329abbc1947b"
original_class_hash = "0x3ca17c0ebb595e1d1cc01813923864316a49b91f4a725ef1371329abbc1947b"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Message-1bb1d226.json"
tag = "dojo_examples-Message"
manifest_name = "dojo_examples-Message-1bb1d226"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x1dfb7c80100d8045d0b37d01ee118e057aa04ff98198f43f1b43171acb0ad9e"
original_class_hash = "0x1dfb7c80100d8045d0b37d01ee118e057aa04ff98198f43f1b43171acb0ad9e"
abi = "manifests/dev/deployment/abis/models/dojo_examples-MockToken-38903c7c.json"
tag = "dojo_examples-MockToken"
manifest_name = "dojo_examples-MockToken-38903c7c"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71f21bb9f7454ede4f4fe1482012218ef57448ca9687018dab409c4ddb790a2"
original_class_hash = "0x71f21bb9f7454ede4f4fe1482012218ef57448ca9687018dab409c4ddb790a2"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moved-318ae40d.json"
tag = "dojo_examples-Moved"
manifest_name = "dojo_examples-Moved-318ae40d"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2bfdf50f9ec0670b52065947e6ce2e1ebb39d54d19da1b65411b6d58bb04e79"
original_class_hash = "0x2bfdf50f9ec0670b52065947e6ce2e1ebb39d54d19da1b65411b6d58bb04e79"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moves-2e2accba.json"
tag = "dojo_examples-Moves"
manifest_name = "dojo_examples-Moves-2e2accba"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5191a56dc5a83bb56969ddb5fcc70dc1ac4ad057d0a054cf555a0023b454923"
original_class_hash = "0x5191a56dc5a83bb56969ddb5fcc70dc1ac4ad057d0a054cf555a0023b454923"
abi = "manifests/dev/deployment/abis/models/dojo_examples-PlayerConfig-3adad785.json"
tag = "dojo_examples-PlayerConfig"
manifest_name = "dojo_examples-PlayerConfig-3adad785"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5af60d63e6a1d25fc117fde1fa7e1d628adc46a52c3d007541ed6dd369e8ea"
original_class_hash = "0x5af60d63e6a1d25fc117fde1fa7e1d628adc46a52c3d007541ed6dd369e8ea"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Position-1e145e26.json"
tag = "dojo_examples-Position"
manifest_name = "dojo_examples-Position-1e145e26"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fa72f20995710bef20ac3c36e2f43ec210517a787927ea3407e2b29c21bb0b"
original_class_hash = "0x2fa72f20995710bef20ac3c36e2f43ec210517a787927ea3407e2b29c21bb0b"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ServerProfile-4caad1e6.json"
tag = "dojo_examples-ServerProfile"
manifest_name = "dojo_examples-ServerProfile-4caad1e6"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "server_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x72898823e557f2f3a48026a97b6ec9fed750a4884788751c4c512c6dde0ff3c"
original_class_hash = "0x72898823e557f2f3a48026a97b6ec9fed750a4884788751c4c512c6dde0ff3c"
abi = "manifests/dev/deployment/abis/models/dojo_examples_foes-RiverSkale-39535c12.json"
tag = "dojo_examples_foes-RiverSkale"
manifest_name = "dojo_examples_foes-RiverSkale-39535c12"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "armor"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5cbece2ac875c6040300d7530bada7a3469a0e8e7584f29fcfaa2626ca1f6de"
original_class_hash = "0x5cbece2ac875c6040300d7530bada7a3469a0e8e7584f29fcfaa2626ca1f6de"
abi = "manifests/dev/deployment/abis/models/dojo_examples_weapons-Flatbow-22f5bd16.json"
tag = "dojo_examples_weapons-Flatbow"
manifest_name = "dojo_examples_weapons-Flatbow-22f5bd16"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "atk_speek"
type = "u32"
key = false

[[models.members]]
name = "range"
type = "u32"
key = false
