[world]
kind = "WorldContract"
class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
original_class_hash = "0x6f38d5d9507c5d9546290e1a27e309efe5a9af3770b6cc1627db4a1b90a7dce"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x46c1fd10836a8426197bf412fc5f26ea10f11a8d5c61474407f03f82c096593"
transaction_hash = "0x7f540b040b1638b76a7f2a8fc13a33050d1c0556a63814f319a01d022b172cf"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x7fed9d6acaa45011152ea992784d41df3ae74eedbc199feb91b3fcbdb78abad"
class_hash = "0x2aaecb3ded9ebb721f13780007e9704cba0d96b48195f357a35f4969d1b1941"
original_class_hash = "0x2aaecb3ded9ebb721f13780007e9704cba0d96b48195f357a35f4969d1b1941"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = ["ns:dojo_examples"]
init_calldata = []
tag = "dojo_examples-actions"
systems = [
    "set_models",
    "spawn",
    "move",
    "set_player_config",
    "reset_player_config",
    "set_player_server_profile",
    "enter_dungeon",
    "update_player_name",
    "update_player_items",
]
manifest_name = "dojo_examples-actions-40b6994c"

[[contracts]]
kind = "DojoContract"
address = "0x47dcd4e30618d32fd27951e977df1d819d6edff2506e52c653f658134062036"
class_hash = "0x117e4d75bef86d66e413d13f30904d2c93798f513ffa0bf83b4fac3fdfc4a62"
original_class_hash = "0x117e4d75bef86d66e413d13f30904d2c93798f513ffa0bf83b4fac3fdfc4a62"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-dungeon-6620e0e6.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-dungeon"
systems = ["enter"]
manifest_name = "dojo_examples-dungeon-6620e0e6"

[[contracts]]
kind = "DojoContract"
address = "0x71c327d19b2d0c6a0f65cced59f60fe69776af6885e8f42d8f6775af00f5d5b"
class_hash = "0x3ad65950996d7b0bc6c04a94d401cdb19bda3ab2cffc2098d90e25077dfa11a"
original_class_hash = "0x3ad65950996d7b0bc6c04a94d401cdb19bda3ab2cffc2098d90e25077dfa11a"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-mock_token-31599eb2.json"
reads = []
writes = ["ns:dojo_examples"]
init_calldata = []
tag = "dojo_examples-mock_token"
systems = []
manifest_name = "dojo_examples-mock_token-31599eb2"

[[contracts]]
kind = "DojoContract"
address = "0x6a116545acc77daea729bf5f14a71f634ddddedb7e7e77f280d8d984054edaf"
class_hash = "0x2331b72955719869459bdacf66061a55975d6c2bc379349b082ee9d9a350a18"
original_class_hash = "0x2331b72955719869459bdacf66061a55975d6c2bc379349b082ee9d9a350a18"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
init_calldata = [
    "$contract_address:dojo_examples-actions",
    "$class_hash:dojo_examples-actions",
    "10",
]
tag = "dojo_examples-others"
systems = []
manifest_name = "dojo_examples-others-61de2c18"

[[models]]
kind = "DojoModel"
class_hash = "0x720bb4a3a1324dea862ac8b3ac3e30ac55490ce6ec9f7f68341db081b290c08"
original_class_hash = "0x720bb4a3a1324dea862ac8b3ac3e30ac55490ce6ec9f7f68341db081b290c08"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ContractInitialized-376b7bd6.json"
tag = "dojo_examples-ContractInitialized"
qualified_path = "dojo_examples::others::others::contract_initialized"
manifest_name = "dojo_examples-ContractInitialized-376b7bd6"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x3ca17c0ebb595e1d1cc01813923864316a49b91f4a725ef1371329abbc1947b"
original_class_hash = "0x3ca17c0ebb595e1d1cc01813923864316a49b91f4a725ef1371329abbc1947b"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Message-1bb1d226.json"
tag = "dojo_examples-Message"
qualified_path = "dojo_examples::models::message"
manifest_name = "dojo_examples-Message-1bb1d226"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x244a875f2049e4ca875b631270f1203a5be374fc040a8c4bd40405eeeea07bd"
original_class_hash = "0x244a875f2049e4ca875b631270f1203a5be374fc040a8c4bd40405eeeea07bd"
abi = "manifests/dev/deployment/abis/models/dojo_examples-MockToken-38903c7c.json"
tag = "dojo_examples-MockToken"
qualified_path = "dojo_examples::models::mock_token"
manifest_name = "dojo_examples-MockToken-38903c7c"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x71f21bb9f7454ede4f4fe1482012218ef57448ca9687018dab409c4ddb790a2"
original_class_hash = "0x71f21bb9f7454ede4f4fe1482012218ef57448ca9687018dab409c4ddb790a2"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moved-318ae40d.json"
tag = "dojo_examples-Moved"
qualified_path = "dojo_examples::actions::actions::moved"
manifest_name = "dojo_examples-Moved-318ae40d"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4dd1c573b5cdc56561be8b28a4840048a3a008d1a4a6eed397ec4135effaf44"
original_class_hash = "0x4dd1c573b5cdc56561be8b28a4840048a3a008d1a4a6eed397ec4135effaf44"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Moves-2e2accba.json"
tag = "dojo_examples-Moves"
qualified_path = "dojo_examples::models::moves"
manifest_name = "dojo_examples-Moves-2e2accba"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x515f106010313c2fcd87719836e75873aa75a711a4bdcd2ea0b6e38854deebf"
original_class_hash = "0x515f106010313c2fcd87719836e75873aa75a711a4bdcd2ea0b6e38854deebf"
abi = "manifests/dev/deployment/abis/models/dojo_examples-PlayerConfig-3adad785.json"
tag = "dojo_examples-PlayerConfig"
qualified_path = "dojo_examples::models::player_config"
manifest_name = "dojo_examples-PlayerConfig-3adad785"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5af60d63e6a1d25fc117fde1fa7e1d628adc46a52c3d007541ed6dd369e8ea"
original_class_hash = "0x5af60d63e6a1d25fc117fde1fa7e1d628adc46a52c3d007541ed6dd369e8ea"
abi = "manifests/dev/deployment/abis/models/dojo_examples-Position-1e145e26.json"
tag = "dojo_examples-Position"
qualified_path = "dojo_examples::models::position"
manifest_name = "dojo_examples-Position-1e145e26"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x2fa72f20995710bef20ac3c36e2f43ec210517a787927ea3407e2b29c21bb0b"
original_class_hash = "0x2fa72f20995710bef20ac3c36e2f43ec210517a787927ea3407e2b29c21bb0b"
abi = "manifests/dev/deployment/abis/models/dojo_examples-ServerProfile-4caad1e6.json"
tag = "dojo_examples-ServerProfile"
qualified_path = "dojo_examples::models::server_profile"
manifest_name = "dojo_examples-ServerProfile-4caad1e6"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "server_id"
type = "u32"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x4f3cbb247febb63bf5ab34d87504fd85e7a3b4ab6ff16fa2bf23597bf3309c7"
original_class_hash = "0x4f3cbb247febb63bf5ab34d87504fd85e7a3b4ab6ff16fa2bf23597bf3309c7"
abi = "manifests/dev/deployment/abis/models/dojo_examples_foes-RiverSkale-39535c12.json"
tag = "dojo_examples_foes-RiverSkale"
qualified_path = "bestiary::river_skale"
manifest_name = "dojo_examples_foes-RiverSkale-39535c12"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "health"
type = "u32"
key = false

[[models.members]]
name = "armor"
type = "u32"
key = false

[[models.members]]
name = "attack"
type = "u32"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x783cecd986c0f03f8ac70318f67d57ea8072db7d4d135d54585f4de33c879ad"
original_class_hash = "0x783cecd986c0f03f8ac70318f67d57ea8072db7d4d135d54585f4de33c879ad"
abi = "manifests/dev/deployment/abis/models/dojo_examples_weapons-Flatbow-22f5bd16.json"
tag = "dojo_examples_weapons-Flatbow"
qualified_path = "armory::flatbow"
manifest_name = "dojo_examples_weapons-Flatbow-22f5bd16"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "atk_speek"
type = "u32"
key = false

[[models.members]]
name = "range"
type = "u32"
key = false
