[package]
description = "Cairo compiler plugin for Dojo."
edition.workspace = true
license-file.workspace = true
name = "dojo-lang"
repository.workspace = true
version.workspace = true

[features]
testing = [  ]

[dependencies]
anyhow.workspace = true
cairo-lang-defs.workspace = true
cairo-lang-diagnostics.workspace = true
cairo-lang-filesystem.workspace = true
cairo-lang-plugins.workspace = true
cairo-lang-semantic.workspace = true
cairo-lang-syntax.workspace = true
cairo-lang-utils.workspace = true
dojo-types.workspace = true
itertools.workspace = true
regex.workspace = true
serde.workspace = true
smol_str.workspace = true
starknet.workspace = true
starknet-crypto.workspace = true
tracing.workspace = true

[dev-dependencies]
cairo-lang-semantic.workspace = true
cairo-lang-parser.workspace = true
