[package]
description = "Torii graphql implementation."
edition.workspace = true
license-file.workspace = true
name = "torii-graphql"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-graphql = { version = "6.0.7", features = [ "chrono", "dynamic-schema" ] }
async-graphql-warp = "6.0.7"
async-recursion = "1.0.5"
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
convert_case = "0.6.0"
dojo-types = { path = "../../dojo-types" }
lazy_static.workspace = true
regex.workspace = true
scarb-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
sozo-ops.workspace = true
sqlx.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio-stream = "0.1.11"
tokio-util = "0.7.7"
tokio.workspace = true
toml.workspace = true
torii-core = { path = "../core" }
tracing.workspace = true
url.workspace = true
warp.workspace = true

[dev-dependencies]
camino.workspace = true
dojo-test-utils = { path = "../../dojo-test-utils", features = [ "build-examples" ] }
dojo-world = { path = "../../dojo-world" }
scarb.workspace = true
serial_test = "2.0.0"
starknet-crypto.workspace = true
starknet.workspace = true
