[package]
edition.workspace = true
license-file.workspace = true
name = "dojo-test-utils"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
assert_fs.workspace = true
async-trait.workspace = true
camino.workspace = true
katana-core = { workspace = true }
katana-executor = { workspace = true, features = [ "blockifier" ] }
katana-node.workspace = true
katana-primitives = { workspace = true }
katana-rpc.workspace = true
scarb.workspace = true
scarb-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
thiserror.workspace = true
toml.workspace = true
url.workspace = true

[build-dependencies]
assert_fs.workspace = true
camino.workspace = true
scarb.workspace = true
scarb-ui.workspace = true

[features]
build-examples = [  ]
