[package]
description = "Collection of Cairo language dependencies that are used throughout Katana. Unifying the Cairo language based dependencies to avoid dependency conflict with the versions used by Dojo."
edition.workspace = true
license.workspace = true
name = "katana-cairo"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Use from git instead of crates.io registry so that the workspace patches aren't applied.
[dependencies]
cairo-lang-casm = "=2.8.2"
cairo-lang-runner = "=2.8.2"
cairo-lang-sierra = "=2.8.2"
cairo-lang-sierra-to-casm = "=2.8.2"
cairo-lang-starknet = "=2.8.2"
cairo-lang-starknet-classes = "=2.8.2"
cairo-lang-utils = "=2.8.2"
cairo-vm.workspace = true
starknet_api = { git = "https://github.com/dojoengine/sequencer", tag = "v0.8.0-rc3.1" }
