[package]
cairo-version = "=2.10.1"
edition = "2024_07"
description = "Testing library for Dojo using Cairo test runner."
name = "dojo_cairo_test"
version = "1.6.1"

[[target.starknet-contract]]
build-external-contracts = [ "dojo::world::world_contract::world" ]

[dependencies]
starknet = "=2.10.1"
dojo = { path = "../core" }

[dev-dependencies]
cairo_test = "=2.10.1"

[lib]
