[package]
cairo-version = "=2.8.2"
edition = "2024_07"
description = "Testing library for Dojo using Cairo test runner."
name = "dojo_cairo_test"
version = "1.0.0-rc.0"

[dependencies]
starknet = "=2.8.2"
dojo = { path = "../core" }

[dev-dependencies]
cairo_test = "=2.8.2"

[lib]
