[package]
cairo-version = "=2.11.4"
edition = "2024_07"
description = "Testing library for Dojo using Cairo test runner."
name = "dojo_cairo_test"
version = "1.0.12"

[[target.starknet-contract]]
build-external-contracts = [ "dojo::world::world_contract::world" ]

[dependencies]
starknet = "=2.11.4"
dojo = { path = "../core" }

[dev-dependencies]
cairo_test = "=2.11.4"

[lib]
