[package]
description = "Dojo specific bindings generator based on Cainome."
edition.workspace = true
license-file.workspace = true
name = "dojo-bindgen"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
camino.workspace = true
chrono.workspace = true
convert_case.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
thiserror.workspace = true

# Some issue with CI on windows, need to be investigated.
# https://github.com/dojoengine/dojo/actions/runs/7736050751/job/21092743552?pr=1501#step:6:249
# dojo-test-utils = { path = "../dojo-test-utils", features = [ "build-examples" ] }

cainome.workspace = true
dojo-world.workspace = true

[dev-dependencies]
assert_matches.workspace = true
dojo-test-utils = { workspace = true, features = [ "build-examples" ] }
scarb-interop.workspace = true
scarb-metadata.workspace = true
scarb-metadata-ext.workspace = true
tokio.workspace = true
