[package]
cairo-version = "2.3.1"
description = "Implementations of common primitives for the Dojo games"
name = "dojo_primitives"
version = "0.3.2"

[lib]

[dependencies]
dojo = { path = "../dojo-core" }

[[target.dojo]]
