[package]
description = "Katana RPC Implementation."
edition.workspace = true
license-file.workspace = true
name = "katana-rpc"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1.0.40"
blockifier.workspace = true
cairo-lang-starknet.workspace = true
cairo-vm.workspace = true
flate2.workspace = true
hex = { version = "0.4.3", default-features = false }
hyper = "0.14.20"
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
katana-core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
starknet.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.0", features = ["full"] }
tracing.workspace = true

[dev-dependencies]
assert_matches = "1.5.0"
dojo-test-utils = { path = "../../dojo-test-utils" }
starknet.workspace = true
url = "2.3.1"
