[package]
edition.workspace = true
name = "torii-server"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
base64.workspace = true
camino.workspace = true
data-url.workspace = true
http-body = "0.4.5"
http.workspace = true
hyper-reverse-proxy = { git = "https://github.com/tarrencev/hyper-reverse-proxy" }
hyper.workspace = true
image.workspace = true
indexmap.workspace = true
lazy_static.workspace = true
mime_guess.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
tokio-util = "0.7.7"
tokio.workspace = true
torii-sqlite.workspace = true
tower-http.workspace = true
tower.workspace = true
tracing.workspace = true
warp.workspace = true
form_urlencoded = "1.2.1"
async-trait = "0.1.83"
tokio-tungstenite = "0.20.0"
hyper-tungstenite = "0.11.1"
futures-util.workspace = true
tokio-stream = "0.1.17"
uuid = "1.15.1"
