[package]
edition = "2021"
name = "torii-server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-graphql = { version = "5.0.8", features = [ "chrono", "dynamic-schema" ] }
async-graphql-poem = "5.0.8"
async-trait.workspace = true
base64 = "0.21.2"
camino.workspace = true
chrono.workspace = true
clap.workspace = true
ctrlc = "3.2.5"
dojo-types = { path = "../../dojo-types" }
dojo-world = { path = "../../dojo-world" }
indexmap = "1.9.3"
log = "0.4.17"
poem = "1.3.48"
scarb.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx = { version = "0.6.2", features = [ "chrono", "macros", "offline", "runtime-actix-rustls", "uuid" ] }
starknet-crypto.workspace = true
starknet.workspace = true
tokio = { version = "1.20.1", features = [ "full" ] }
tokio-stream = "0.1.11"
tokio-util = "0.7.7"
torii-core = { path = "../core" }
torii-graphql = { path = "../graphql" }
tracing-subscriber.workspace = true
tracing.workspace = true
url = "2.2.2"

[dev-dependencies]
camino.workspace = true

[features]
default = [ "sqlite" ]
sqlite = [ "sqlx/sqlite" ]

[[bin]]
name = "torii"
path = "src/cli.rs"
