[package]
edition.workspace = true
name = "torii-server"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64 = "0.21.2"
camino.workspace = true
chrono.workspace = true
clap.workspace = true
ctrlc = { version = "3.4", features = [ "termination" ] }
dojo-types = { path = "../../dojo-types" }
dojo-world = { path = "../../dojo-world" }
either = "1.9.0"
futures.workspace = true
http = "0.2.9"
http-body = "0.4.5"
hyper-reverse-proxy = { git = "https://github.com/tarrencev/hyper-reverse-proxy" }
hyper.workspace = true
indexmap = "1.9.3"
lazy_static.workspace = true
metrics = { path = "../../metrics" }
metrics-process.workspace = true
scarb.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
starknet-crypto.workspace = true
starknet.workspace = true
tokio-stream = "0.1.11"
tokio-util = "0.7.7"
tokio.workspace = true
torii-core = { path = "../core" }
torii-graphql = { path = "../graphql" }
torii-grpc = { path = "../grpc", features = [ "server" ] }
tower = "0.4.13"
tower-http = "0.4.4"
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
camino.workspace = true

[features]
default = [ "jemalloc", "sqlite" ]
jemalloc = [ "metrics/jemalloc" ]
sqlite = [ "sqlx/sqlite" ]
