kind = "DojoContract"
class_hash = "0x412449a631f6652b3bbe27841fb6776639e493baad1a5894daeb9260d1b0a63"
original_class_hash = "0x412449a631f6652b3bbe27841fb6776639e493baad1a5894daeb9260d1b0a63"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/ccf-cairo_v260-465ec7fe.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "ccf-cairo_v260"
manifest_name = "ccf-cairo_v260-465ec7fe"
