[package]
description = "Commonly used types in Katana"
edition.workspace = true
name = "katana-primitives"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
base64.workspace = true
cairo-vm.workspace = true
derive_more.workspace = true
lazy_static = "1.4.0"
rand = { version = "0.8.5", features = [ "small_rng" ] }
rayon.workspace = true
serde.workspace = true
serde_json = { workspace = true, features = [ "arbitrary_precision" ] }
serde_with.workspace = true
starknet.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

blockifier.workspace = true
cairo-lang-sierra.workspace = true
cairo-lang-starknet.workspace = true
flate2.workspace = true
starknet_api.workspace = true

ethers = "2.0.11"

[features]
default = [ "blockifier", "serde" ]

blockifier = [  ]
rpc = [  ]
serde = [  ]
