[package]
description = "Commonly used types in Katana"
edition.workspace = true
name = "katana-primitives"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
base64.workspace = true
derive_more.workspace = true
lazy_static.workspace = true
rand = { workspace = true, features = [ "small_rng" ] }
rayon.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
starknet-crypto.workspace = true
starknet.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true

alloy-primitives.workspace = true
flate2.workspace = true
katana-cairo.workspace = true
starknet_api.workspace = true

[dev-dependencies]
similar-asserts.workspace = true

[features]
default = [ "serde" ]
rpc = [  ]
serde = [ "alloy-primitives/serde" ]
