[package]
name = "dojo_cairo_test"
description = "Testing library for Dojo using cairo test runner."

version = "1.6.0-alpha.1"
edition = "2024_07"
cairo-version = "=2.12.0"

[dependencies]
starknet = "=2.12.0"
cairo_test = "=2.12.0"

dojo = { path = "../core" }

[lib]
