[package]
name = "dojo_cairo_test"
description = "Testing library for Dojo using cairo test runner."

version = "1.6.0"
edition = "2024_07"
cairo-version = "=2.11.4"

[dependencies]
starknet = "=2.11.4"
cairo_test = "=2.11.4"

dojo = { path = "../core" }

[lib]
