[package]
edition.workspace = true
name = "dojo-utils"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
futures.workspace = true
reqwest.workspace = true
rpassword.workspace = true
starknet.workspace = true
thiserror.workspace = true
tokio = { version = "1", features = [ "signal", "time" ], default-features = false }

[dev-dependencies]
assert_matches.workspace = true
dojo-test-utils.workspace = true
