kind = "DojoContract"
class_hash = "0x67edb33671cd2f5b766d073e3dec53b03400761a20f349ea9628cf4c883b393"
original_class_hash = "0x67edb33671cd2f5b766d073e3dec53b03400761a20f349ea9628cf4c883b393"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_examples-mock_token-31599eb2.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-mock_token"
systems = []
interface_path = ""
manifest_name = "dojo_examples-mock_token-31599eb2"
