kind = "DojoContract"
class_hash = "0x2c975b0d681861edd6caad5fbc0b42dc3e8b034b6c0b0a7628fb3a7bedf1e8d"
original_class_hash = "0x2c975b0d681861edd6caad5fbc0b42dc3e8b034b6c0b0a7628fb3a7bedf1e8d"
base_class_hash = "0x0"
abi = 'manifests\dev\base\abis\contracts\dojo_examples-actions-40b6994c.json'
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-actions"
manifest_name = "dojo_examples-actions-40b6994c"
