kind = "DojoContract"
class_hash = "0x15679777d999d9981b48c2b6d7db0bded1743d20fa037f8ccb61926c421f8c6"
original_class_hash = "0x15679777d999d9981b48c2b6d7db0bded1743d20fa037f8ccb61926c421f8c6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
computed = []
init_calldata = []
tag = "dojo_examples-others"
manifest_name = "dojo_examples-others-61de2c18"
