kind = "DojoContract"
class_hash = "0x4590a27e4ec7366358ba5f60323777f301435ebbdd113ab02c54b947717530d"
original_class_hash = "0x4590a27e4ec7366358ba5f60323777f301435ebbdd113ab02c54b947717530d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_examples-dungeon-6620e0e6.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-dungeon"
systems = ["enter"]
interface_path = "dojo_examples::dungeon::IDungeon"
manifest_name = "dojo_examples-dungeon-6620e0e6"
