kind = "DojoContract"
class_hash = "0x491920188044edfc9bb9ba1d0f989b10e9791d91089a6a98413f5dbf54579cb"
original_class_hash = "0x491920188044edfc9bb9ba1d0f989b10e9791d91089a6a98413f5dbf54579cb"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples_actions_actions.json"
reads = []
writes = []
computed = []
constructor_calldata = []
name = "dojo_examples::actions::actions"
