kind = "DojoContract"
class_hash = "0x471a1a36581d24f68ae6984c714daa75d424c0a6581872a65e645eb11a8e45"
original_class_hash = "0x471a1a36581d24f68ae6984c714daa75d424c0a6581872a65e645eb11a8e45"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples::actions::actions.json"
reads = []
writes = []
computed = []
name = "dojo_examples::actions::actions"
