kind = "DojoContract"
class_hash = "0x40e824b8814bafef18cce2cf68f5765e9c9a1c86f55a8491b0c2a4faebdcc87"
original_class_hash = "0x40e824b8814bafef18cce2cf68f5765e9c9a1c86f55a8491b0c2a4faebdcc87"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_examples-others-61de2c18.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-others"
systems = []
interface_path = ""
manifest_name = "dojo_examples-others-61de2c18"
