kind = "DojoContract"
class_hash = "0x67a20ea91a4b9bb9cdb46cefc41dd6ca4c07c22d4d413205720963944fd817d"
original_class_hash = "0x67a20ea91a4b9bb9cdb46cefc41dd6ca4c07c22d4d413205720963944fd817d"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/dojo_examples-actions-40b6994c.json"
reads = []
writes = []
init_calldata = []
tag = "dojo_examples-actions"
systems = [
    "set_models",
    "spawn",
    "move",
    "set_player_config",
    "reset_player_config",
    "set_player_server_profile",
    "enter_dungeon",
    "update_player_name",
    "update_player_items",
]
interface_path = "dojo_examples::actions::IActions"
manifest_name = "dojo_examples-actions-40b6994c"
