kind = "DojoModel"
class_hash = "0x2fa72f20995710bef20ac3c36e2f43ec210517a787927ea3407e2b29c21bb0b"
original_class_hash = "0x2fa72f20995710bef20ac3c36e2f43ec210517a787927ea3407e2b29c21bb0b"
abi = "manifests/dev/base/abis/models/dojo_examples-ServerProfile-4caad1e6.json"
tag = "dojo_examples-ServerProfile"
qualified_path = "dojo_examples::models::server_profile"
manifest_name = "dojo_examples-ServerProfile-4caad1e6"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "server_id"
type = "u32"
key = true

[[members]]
name = "name"
type = "ByteArray"
key = false
