kind = "DojoModel"
class_hash = "0x1da39caefeb15d61baa9d1d71f21ed79cf5650aa215b583e7f453c0d7d4ee65"
original_class_hash = "0x1da39caefeb15d61baa9d1d71f21ed79cf5650aa215b583e7f453c0d7d4ee65"
abi = 'manifests\dev\base\abis\models\dojo_examples-ContractInitialized-376b7bd6.json'
tag = "dojo_examples-ContractInitialized"
manifest_name = "dojo_examples-ContractInitialized-376b7bd6"

[[members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[members]]
name = "contract_class"
type = "ClassHash"
key = false

[[members]]
name = "value"
type = "u8"
key = false
