[package]
edition = "2021"
name = "dojo-client"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dojo-types = { path = "../dojo-types" }
dojo-world = { path = "../dojo-world" }
starknet-crypto.workspace = true
starknet.workspace = true
thiserror.workspace = true

[dev-dependencies]
camino.workspace = true
dojo-test-utils = { path = "../dojo-test-utils" }
tokio.workspace = true
