[package]
description = "Helper functions for building types used in Katana RPC."
edition.workspace = true
name = "katana-rpc-types-builder"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-types.workspace = true
starknet.workspace = true

anyhow.workspace = true
