[workspace]
members = [
    "armory",
    "bestiary"
]

[workspace.package]
version = "0.1.0"
description = "Example game library for Dojo"
edition = "2024_07"
cairo-version = "=2.11.4"

[workspace.dependencies]
dojo = { path = "../../crates/dojo/core/" }
