[package]
description = "Katana database implementation"
edition.workspace = true
name = "katana-db"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
katana-primitives = { workspace = true, features = [ "arbitrary" ] }
katana-trie.workspace = true

anyhow.workspace = true
dojo-metrics.workspace = true
metrics.workspace = true
page_size = "0.6.0"
parking_lot.workspace = true
roaring = { version = "0.10.3", features = [ "serde" ] }
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true

# codecs
postcard = { workspace = true, optional = true }
smallvec = "1.13.2"

[dependencies.libmdbx]
git = "https://github.com/paradigmxyz/reth.git"
package = "reth-libmdbx"
rev = "b34b0d3"

[dev-dependencies]
arbitrary.workspace = true
criterion.workspace = true
proptest = "1.6.0"
rstest.workspace = true
starknet.workspace = true

[features]
default = [ "postcard" ]
postcard = [ "dep:postcard" ]
test-utils = [  ]

[[bench]]
harness = false
name = "codec"
