[package]
edition = "2021"
name = "torii-client"
version = "0.2.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.12.0", default-features = false, features = [ "std" ] }
async-trait.workspace = true
crypto-bigint = "0.5.3"
dojo-types = { path = "../../dojo-types" }
parking_lot = "0.12.1"
starknet-crypto.workspace = true
starknet.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1.16", features = [ "time" ], default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.64"
serde.workspace = true
wasm-bindgen = "0.2.87"
wasm-bindgen-futures = "0.4.37"
web-sys = { version = "0.3.4", features = [ 'Window', 'WorkerGlobalScope' ] }

[dev-dependencies]
camino.workspace = true
dojo-test-utils = { path = "../../dojo-test-utils", features = [ "build-examples" ] }
dojo-world = { path = "../../dojo-world" }
tokio.workspace = true
