[package]
edition.workspace = true
name = "katana-runner-macro"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0"
strum.workspace = true
strum_macros.workspace = true
syn = { version = "2.0", features = [ "fold", "full" ] }

[dev-dependencies]
starknet.workspace = true
