kind = "DojoModel"
class_hash = "0x511fbd833938f5c4b743eea1e67605a125d7ff60e8a09e8dc227ad2fb59ca54"
name = "dojo_examples::models::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
