[package]
description = "Utilities for working with the Katana binary"
edition.workspace = true
license-file.workspace = true
name = "katana-node-bindings"
repository.workspace = true
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true

[dev-dependencies]
criterion.workspace = true
pprof.workspace = true
tempfile.workspace = true
tokio.workspace = true

[[bench]]
harness = false
name = "startup"
