[package]
edition.workspace = true
license.workspace = true
name = "torii-cli"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
dojo-utils.workspace = true
serde.workspace = true
starknet.workspace = true
toml.workspace = true
torii-sqlite-types.workspace = true
url.workspace = true
merge-options.workspace = true

[dev-dependencies]
assert_matches.workspace = true
camino.workspace = true

[features]
default = [ "server" ]
server = [  ]
