[package]
name = "dojo_physics"
version = "0.1.0"
cairo-version = "2.0.0-rc1"
description = "Implementations of a physics library for the Dojo framework"

[dependencies]
dojo_core = { path = "../dojo-core" }
cubit = { git = "https://github.com/influenceth/cubit" }

[[target.dojo]]
