[package]
name = "armory"
version = "0.1.0"
description = "An armory of epic weapons."

[dependencies]
dojo.workspace = true

[lib]

[[target.dojo]]

[tool.dojo.world]
name = "armory"
seed = "armory"
namespace = "armory"
