[package]
name = "armory"
version = "1.6.0-alpha.0"
description = "An armory of epic weapons."
edition.workspace = true
cairo-version.workspace = true

[dependencies]
starknet.workspace = true
dojo.workspace = true
dojo_macros.workspace = true

[dev-dependencies]
cairo_test = "2.11.4"
dojo_cairo_test = { path = "../../../crates/dojo/dojo-cairo-test" }

[lib]
