[package]
edition.workspace = true
license.workspace = true
name = "katana-stage"
repository.workspace = true
version.workspace = true

[dependencies]
katana-core.workspace = true
katana-executor.workspace = true
katana-feeder-gateway.workspace = true
katana-messaging.workspace = true
katana-pool.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-types.workspace = true
katana-tasks.workspace = true

anyhow.workspace = true
async-trait.workspace = true
backon = { version = "1.3.0", features = [ "tokio-sleep" ] }
futures.workspace = true
num-traits.workspace = true
starknet.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
