[package]
edition.workspace = true
name = "katana-codecs"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.5.0"
katana-primitives = { path = "../../primitives" }
