[package]
cairo-version = "=2.9.2"
edition = "2024_07"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "1.0.11"

[dependencies]
starknet = "=2.9.2"
dojo_plugin = { path = "../lang" }
#dojo_macros = { path = "../macros" }

[dev-dependencies]
cairo_test = "=2.9.2"

[lib]

[[target.starknet-contract]]
sierra = true
