[package]
cairo-version = "=2.10.1"
edition = "2024_07"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "1.6.2"

[dependencies]
starknet = "=2.10.1"
dojo_plugin = { path = "../lang" }
#dojo_macros = { path = "../macros" }

[dev-dependencies]
cairo_test = "=2.10.1"

[lib]

[[target.starknet-contract]]
sierra = true
