[package]
cairo-version = "=2.9.4"
edition = "2024_07"
description = "The Dojo Core library for autonomous worlds."
name = "dojo"
version = "1.4.0"

[dependencies]
starknet = "=2.9.4"
dojo_plugin = { path = "../lang" }
#dojo_macros = { path = "../macros" }

[dev-dependencies]
cairo_test = "=2.9.4"

[lib]

[[target.starknet-contract]]
sierra = true
