[package]
edition.workspace = true
name = "katana-codecs-derive"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.70"
quote = "1.0.33"
serde.workspace = true
syn = { version = "2.0.41", features = [ "extra-traits", "full" ] }

[package.metadata.cargo-udeps.ignore]
normal = [ "serde" ]
