[package]
edition.workspace = true
license.workspace = true
name = "xtask-generate-test-db"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
dojo-test-utils.workspace = true
dojo-utils.workspace = true
dojo-world.workspace = true
katana-runner.workspace = true
reqwest = { workspace = true, features = [ "json" ] }
scarb-interop.workspace = true
sozo-ops = { workspace = true, features = [ "test-utils" ] }
starknet.workspace = true
tokio.workspace = true
