kind = "DojoModel"
class_hash = "0x7a47c3a9c8509a1d4a0379e50799eba7b173db6e41961341fe3f856a51d627"
abi = "abis/base/models/subrecord.json"
name = "types_test::models::subrecord"

[[members]]
name = "record_id"
type = "u32"
key = true

[[members]]
name = "subrecord_id"
type = "u32"
key = true

[[members]]
name = "type_u8"
type = "u8"
key = false

[[members]]
name = "random_u8"
type = "u8"
key = false
