[package]
edition.workspace = true
name = "katana-runner"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
runner_macro = { path = "./runner-macro" }
anyhow.workspace = true
home = "0.5.5"
lazy_static.workspace = true
starknet.workspace = true
tokio.workspace = true
url.workspace = true
