[package]
edition.workspace = true
name = "katana-runner"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
assert_fs.workspace = true
chrono.workspace = true
home = "0.5.5"
katana-core.workspace = true
katana-primitives.workspace = true
lazy_static.workspace = true
runner-macro = { path = "./runner-macro" }
serde.workspace = true
serde_json.workspace = true
starknet.workspace = true
tokio.workspace = true
url.workspace = true
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "7128c53", features = [
    "network",
    "providers",
    "provider-http",
    "signer-wallet",
    "node-bindings"
] }