[package]
edition.workspace = true
license.workspace = true
license-file.workspace = true
name = "katana-feeder-gateway"
repository.workspace = true
version.workspace = true

[dependencies]
katana-primitives.workspace = true
katana-rpc-types.workspace = true

reqwest.workspace = true
serde.workspace = true
starknet.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
serde_json.workspace = true
tokio.workspace = true
