[package]
edition = "2021"
name = "runner-macro"
version = "1.0.0-alpha.13"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
quote = "1.0.35"
syn = { version = "2.0.48", features = [ "fold", "full" ] }
