kind = "DojoContract"
class_hash = "0x2a3b1c5473dfb9fd1be08b94fae201b30b4e63ed8caed996476cc4ad44cadb2"
original_class_hash = "0x2a3b1c5473dfb9fd1be08b94fae201b30b4e63ed8caed996476cc4ad44cadb2"
base_class_hash = "0x0"
abi = "abis/base/contracts/actions.json"
reads = []
writes = []
computed = []
name = "dojo_examples::actions::actions"
