[package]
description = "Dojo world specification. For example, crates and flags used for compilation."
edition.workspace = true
license-file.workspace = true
name = "dojo-world"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cairo-lang-filesystem.workspace = true
cairo-lang-project.workspace = true
cairo-lang-starknet.workspace = true
camino.workspace = true
convert_case.workspace = true
dojo-types = { path = "../dojo-types" }
futures = "0.3.28"
reqwest = { version = "0.11.18", default-features = false, features = [ "rustls-tls" ] }
scarb.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
smol_str.workspace = true
starknet-crypto.workspace = true
starknet.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url = "2.2.2"

[dev-dependencies]
assert_fs = "1.0.9"
assert_matches = "1.5.0"
dojo-lang = { path = "../dojo-lang" }
dojo-test-utils = { path = "../dojo-test-utils" }
tokio = { version = "1.28.0", features = [ "full" ] }
