[package]
name = "dojo-world"
version.workspace = true
edition.workspace = true
repository.workspace = true
license-file.workspace = true
description = "Dojo world specification. For example, crates and flags used for compilation."

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
cairo-lang-starknet.workspace = true
cairo-lang-project.workspace = true
camino.workspace = true
thiserror.workspace = true
toml = "0.7.1"
cairo-lang-filesystem.workspace = true
scarb.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with = "2.3.1"
smol_str.workspace = true
starknet.workspace = true
url = "2.2.2"
tracing.workspace = true

[dev-dependencies]
assert_fs = "1.0.9"
dojo-lang = { path = "../dojo-lang" }
indoc.workspace = true
katana-core = { git = "https://github.com/dojoengine/katana" }
katana-rpc = { git = "https://github.com/dojoengine/katana" }
test-log.workspace = true
tokio = { version = "1.28.0", features = ["full"] }
