[package]
edition.workspace = true
name = "sozo-walnut"
version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
console.workspace = true
dojo-world.workspace = true
reqwest.workspace = true
scarb.workspace = true
scarb-ui.workspace = true
serde.workspace = true
serde_json.workspace = true
sozo-scarbext.workspace = true
starknet.workspace = true
thiserror.workspace = true
url.workspace = true
urlencoding = "2.1.3"
walkdir.workspace = true

[dev-dependencies]
starknet.workspace = true
