[package]
description = "Transaction pool abstraction and implementation for Katana"
edition.workspace = true
license.workspace = true
name = "katana-pool"
repository.workspace = true
version.workspace = true

[dependencies]
futures.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
rand.workspace = true
