[package]
cairo-version = "=2.9.1"
name = "benches"
version = "1.0.0-rc.0"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-rc.0" }
starknet = "=2.9.1"
