[package]
description = "Saya core implementation."
edition.workspace = true
license-file.workspace = true
name = "saya-core"
repository.workspace = true
version.workspace = true

[dependencies]
katana-db.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-types.workspace = true
saya-provider.workspace = true

anyhow.workspace = true
async-trait.workspace = true
cairo-proof-parser.workspace = true
cairo-vm.workspace = true
convert_case.workspace = true
flate2.workspace = true
futures.workspace = true
lazy_static.workspace = true
parking_lot.workspace = true
rand = { version = "0.8.5", features = [ "small_rng" ] }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
starknet-types-core = { version = "0.0.9", default-features = false, features = [ "curve", "num-traits", "serde" ] }
starknet.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

# TODO: use features for each possible DA.
cairo-lang-utils = "2"
celestia-rpc = "0.1.1"
celestia-types = "0.1.1"

cairo-felt = "0.9.1"
num-bigint = "0.4.4"
