[package]
description = "Saya core implementation."
edition.workspace = true
license-file.workspace = true
name = "saya-core"
repository.workspace = true
version.workspace = true

[dependencies]
katana-db.workspace = true
katana-executor.workspace = true
katana-primitives.workspace = true
katana-provider.workspace = true
katana-rpc-types.workspace = true
saya-provider.workspace = true

anyhow.workspace = true
async-trait.workspace = true
cairo-proof-parser.workspace = true
cairo-vm.workspace = true
convert_case.workspace = true
dojo-world = { workspace = true, features = [ "contracts", "manifest", "metadata", "migration" ] }
flate2.workspace = true
futures.workspace = true
itertools.workspace = true
lazy_static.workspace = true
parking_lot.workspace = true
rand = { workspace = true, features = [ "small_rng" ] }
reqwest = { workspace = true, features = [ "rustls-tls" ] }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
starknet-crypto.workspace = true
starknet-types-core = { version = "0.0.9", default-features = false, features = [ "curve", "num-traits", "serde" ] }
starknet.workspace = true
starknet_api.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true

# TODO: use features for each possible DA.
celestia-rpc = "0.2.0"
celestia-types = "0.2.0"

cairo-felt = "0.9.1"
num-bigint = "0.4.4"
num-traits = "0.2.18"

prover-sdk = { git = "https://github.com/cartridge-gg/http-prover", rev = "7d00b05" }
